fix: correct circulation policy
* Corrects item types and patron_types of circulation policy with pid = 10 and 11.
* Adds test to check data consistency when ci-po are created.
* Adds new patron type.
* Corrects import sorting.
* Closes #625.
* Closes #626.
* Closes #213.

Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch>

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -25,6 +25,8 @@ DATA_PATH=$(pipenv --where)/data
 #       used for create only the items and holdings files for the 'big' documents file
 #  --deployment:
 #       used for deploy the 'big' files
+#  --dont_stop:
+#       used for continue script on error
 
 RED='\033[0;31m'
 GREEN='\033[0;0;32m'
@@ -43,9 +45,10 @@ CREATE_ITEMS_HOLDINGS_SMALL=false
 CREATE_ITEMS_HOLDINGS_BIG=false
 STOP_EXECUTION=true
 CREATE_LAZY=""
+DONT_STOP=""
 
 # options may be followed by one colon to indicate they have a required argument
-if ! options=$(getopt -o dsb -l deployment,create_items_holdings_small,create_items_holdings_big,lazy,data_path: -- "$@")
+if ! options=$(getopt -o dsb -l deployment,create_items_holdings_small,create_items_holdings_big,lazy,dont_stop,data_path: -- "$@")
 then
     # something went wrong, getopt will put out an error message for us
     exit 1
@@ -59,6 +62,7 @@ do
     -b|--create_items_holdings_big) CREATE_ITEMS_HOLDINGS_BIG=true ;;
     -c|--continue) STOP_EXECUTION=false ;;
     -l|--lazy) CREATE_LAZY="--lazy" ;;
+    -p|--pursue) DONT_STOP="--dont-stop" ;;
     -D|--data_path) DATA_PATH=$2 ;;
     (--) shift; break;;
     (-*) display_error_message "$0: error - unrecognized option $1"; exit 1;;
@@ -141,25 +145,25 @@ pipenv run invenio access allow superuser-access role superusers
 pipenv run invenio roles add admin@rero.ch admins
 pipenv run invenio roles add admin@rero.ch superusers
 
-display_success_message "Organisations:"
-pipenv run invenio fixtures create --pid_type org ${DATA_PATH}/organisations.json  --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t org --yes-i-know
-display_success_message "Libraries:"
-pipenv run invenio fixtures create --pid_type lib ${DATA_PATH}/libraries.json --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t lib --yes-i-know
-display_success_message "Locations:"
-pipenv run invenio fixtures create --pid_type loc ${DATA_PATH}/locations.json  --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t loc --yes-i-know
-display_success_message "Item types:"
-pipenv run invenio fixtures create --pid_type itty ${DATA_PATH}/item_types.json  --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t itty --yes-i-know
-display_success_message "Patron types:"
-pipenv run invenio fixtures create --pid_type ptty ${DATA_PATH}/patron_types.json --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t ptty --yes-i-know
-display_success_message "Circulation policies:"
-pipenv run invenio fixtures create --pid_type cipo ${DATA_PATH}/circulation_policies.json --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t cipo --yes-i-know
-pipenv run invenio utils runindex --raise-on-error
+display_success_message "Organisations: ${CREATE_LAZY} ${DONT_STOP}"
+pipenv run invenio fixtures create --pid_type org ${DATA_PATH}/organisations.json --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t org --yes-i-know
+display_success_message "Libraries: ${CREATE_LAZY} ${DONT_STOP}"
+pipenv run invenio fixtures create --pid_type lib ${DATA_PATH}/libraries.json --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t lib --yes-i-know
+display_success_message "Locations: ${CREATE_LAZY} ${DONT_STOP}"
+pipenv run invenio fixtures create --pid_type loc ${DATA_PATH}/locations.json  --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t loc --yes-i-know
+display_success_message "Item types: ${CREATE_LAZY} ${DONT_STOP}"
+pipenv run invenio fixtures create --pid_type itty ${DATA_PATH}/item_types.json  --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t itty --yes-i-know
+display_success_message "Patron types: ${CREATE_LAZY} ${DONT_STOP}"
+pipenv run invenio fixtures create --pid_type ptty ${DATA_PATH}/patron_types.json --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t ptty --yes-i-know
+display_success_message "Circulation policies: ${CREATE_LAZY} ${DONT_STOP}"
+pipenv run invenio fixtures create --pid_type cipo ${DATA_PATH}/circulation_policies.json --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t cipo --yes-i-know
+pipenv run invenio index run --raise-on-error
 
 pipenv run invenio fixtures import_users ${DATA_PATH}/users.json -v
 
@@ -185,9 +189,9 @@ else
     HOLDINGS=${DATA_PATH}/holdings_small.json
 fi
 
-display_success_message "Documents:"
+display_success_message "Documents: ${DONT_STOP}"
 echo -e ${DOCUMENTS}
-pipenv run invenio fixtures create --pid_type doc --schema 'http://ils.rero.ch/schema/documents/document-v0.0.1.json' ${DOCUMENTS} --append
+pipenv run invenio fixtures create --pid_type doc --schema 'http://ils.rero.ch/schema/documents/document-v0.0.1.json' ${DOCUMENTS} --append ${DONT_STOP}
 
 if $CREATE_ITEMS_HOLDINGS_SMALL
 then
@@ -211,17 +215,17 @@ then
     fi
 fi
 
-display_success_message "Holdings: ${CREATE_LAZY}"
+display_success_message "Holdings: ${CREATE_LAZY} ${DONT_STOP}"
 echo -e ${HOLDINGS}
-pipenv run invenio fixtures create --pid_type hold --schema 'http://ils.rero.ch/schema/holdings/holding-v0.0.1.json' ${HOLDINGS} --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t hold --yes-i-know
-pipenv run invenio utils runindex -c 4 --raise-on-error
+pipenv run invenio fixtures create --pid_type hold --schema 'http://ils.rero.ch/schema/holdings/holding-v0.0.1.json' ${HOLDINGS} --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t hold --yes-i-know
+pipenv run invenio index run -c 4 --raise-on-error
 
-display_success_message "Items: ${CREATE_LAZY}"
+display_success_message "Items: ${CREATE_LAZY} ${DONT_STOP}"
 echo -e ${ITEMS}
-pipenv run invenio fixtures create --pid_type item --schema 'http://ils.rero.ch/schema/items/item-v0.0.1.json' ${ITEMS}  --append ${CREATE_LAZY}
-pipenv run invenio utils reindex -t item --yes-i-know
-pipenv run invenio utils runindex -c 4 --raise-on-error
+pipenv run invenio fixtures create --pid_type item --schema 'http://ils.rero.ch/schema/items/item-v0.0.1.json' ${ITEMS} --append ${CREATE_LAZY} ${DONT_STOP}
+pipenv run invenio index reindex -t item --yes-i-know
+pipenv run invenio index run -c 4 --raise-on-error
 
 display_success_message "Index Documents:"
 pipenv run invenio utils reindex -t doc --yes-i-know
